package pocztex.test.packages;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-04-21T22:49:13.691+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "ElektronicznyNadawca", 
                  wsdlLocation = "/home/mszwed/euvic/ws-couriers/src/main/resources/wsdl/pocztex_packages.wsdl",
                  targetNamespace = "http://e-nadawca.poczta-polska.pl") 
public class ElektronicznyNadawca_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://e-nadawca.poczta-polska.pl", "ElektronicznyNadawca");
    public final static QName ENSoap = new QName("http://e-nadawca.poczta-polska.pl", "ENSoap");
    static {
        URL url = null;
        try {
            url = new URL("/home/mszwed/euvic/ws-couriers/src/main/resources/wsdl/pocztex_packages.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ElektronicznyNadawca_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/mszwed/euvic/ws-couriers/src/main/resources/wsdl/pocztex_packages.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ElektronicznyNadawca_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ElektronicznyNadawca_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ElektronicznyNadawca_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ElektronicznyNadawca_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ElektronicznyNadawca_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ElektronicznyNadawca_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ElektronicznyNadawca
     */
    @WebEndpoint(name = "ENSoap")
    public ElektronicznyNadawca getENSoap() {
        return super.getPort(ENSoap, ElektronicznyNadawca.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ElektronicznyNadawca
     */
    @WebEndpoint(name = "ENSoap")
    public ElektronicznyNadawca getENSoap(WebServiceFeature... features) {
        return super.getPort(ENSoap, ElektronicznyNadawca.class, features);
    }

}
