package pocztex.test.packages;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-04-21T22:49:13.661+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://e-nadawca.poczta-polska.pl", name = "ElektronicznyNadawca")
@XmlSeeAlso({ObjectFactory.class})
public interface ElektronicznyNadawca {

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getFirmowaPocztaBook")
    @RequestWrapper(localName = "getFirmowaPocztaBook", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetFirmowaPocztaBook")
    @ResponseWrapper(localName = "getFirmowaPocztaBookResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetFirmowaPocztaBookResponse")
    public void getFirmowaPocztaBook(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createChecklistTemplate")
    @RequestWrapper(localName = "createChecklistTemplate", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateChecklistTemplate")
    @ResponseWrapper(localName = "createChecklistTemplateResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateChecklistTemplateResponse")
    public void createChecklistTemplate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "checklistTemplate", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ChecklistTemplateType>> checklistTemplate,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createParcelContent")
    @RequestWrapper(localName = "createParcelContent", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateParcelContent")
    @ResponseWrapper(localName = "createParcelContentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateParcelContentResponse")
    public void createParcelContent(
        @WebParam(mode = WebParam.Mode.INOUT, name = "parcelContent", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ParcelContentType>> parcelContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateEnvelopeBufor")
    @RequestWrapper(localName = "updateEnvelopeBufor", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateEnvelopeBufor")
    @ResponseWrapper(localName = "updateEnvelopeBuforResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateEnvelopeBuforResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> updateEnvelopeBufor(
        @WebParam(name = "bufor", targetNamespace = "")
        java.util.List<pocztex.test.packages.BuforType> bufor
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/deleteParcelContent")
    @RequestWrapper(localName = "deleteParcelContent", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DeleteParcelContent")
    @ResponseWrapper(localName = "deleteParcelContentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DeleteParcelContentResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> deleteParcelContent(
        @WebParam(name = "parcelContent", targetNamespace = "")
        java.util.List<pocztex.test.packages.ParcelContentType> parcelContent
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddresLabelCompact")
    @RequestWrapper(localName = "getAddresLabelCompact", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddresLabelCompact")
    @ResponseWrapper(localName = "getAddresLabelCompactResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddresLabelCompactResponse")
    public void getAddresLabelCompact(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/changePassword")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ChangePasswordResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> changePassword(
        @WebParam(name = "newPassword", targetNamespace = "")
        java.lang.String newPassword
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeStatus")
    @RequestWrapper(localName = "getEnvelopeStatus", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeStatus")
    @ResponseWrapper(localName = "getEnvelopeStatusResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeStatusResponse")
    public void getEnvelopeStatus(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeStatus", targetNamespace = "")
        javax.xml.ws.Holder<EnvelopeStatusType> envelopeStatus,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAdditionalActivitiesList")
    @RequestWrapper(localName = "getAdditionalActivitiesList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAdditionalActivitiesList")
    @ResponseWrapper(localName = "getAdditionalActivitiesListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAdditionalActivitiesListResponse")
    public void getAdditionalActivitiesList(
        @WebParam(name = "idKarta", targetNamespace = "")
        int idKarta,
        @WebParam(mode = WebParam.Mode.OUT, name = "additionalActivity", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.AdditionalActivityType>> additionalActivity,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getReturnDocumentsProfileList")
    @RequestWrapper(localName = "getReturnDocumentsProfileList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetReturnDocumentsProfileList")
    @ResponseWrapper(localName = "getReturnDocumentsProfileListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetReturnDocumentsProfileListResponse")
    public void getReturnDocumentsProfileList(
        @WebParam(mode = WebParam.Mode.OUT, name = "profile", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ReturnDocumentProfileType>> profile,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/isObszarMiasto")
    @RequestWrapper(localName = "isObszarMiasto", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.IsObszarMiasto")
    @ResponseWrapper(localName = "isObszarMiastoResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.IsObszarMiastoResponse")
    @WebResult(name = "obszarAdresowy", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ObszarAdresowyResponseType> isObszarMiasto(
        @WebParam(name = "adres", targetNamespace = "")
        java.util.List<pocztex.test.packages.ObszarAdresowyType> adres
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getBlankietPobraniaByGuids")
    @RequestWrapper(localName = "getBlankietPobraniaByGuids", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetBlankietPobraniaByGuids")
    @ResponseWrapper(localName = "getBlankietPobraniaByGuidsResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetBlankietPobraniaByGuidsResponse")
    public void getBlankietPobraniaByGuids(
        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "content", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.AddressLabelContent>> content,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getZapowiedziFaktur")
    @RequestWrapper(localName = "getZapowiedziFaktur", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetZapowiedziFaktur")
    @ResponseWrapper(localName = "getZapowiedziFakturResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetZapowiedziFakturResponse")
    @WebResult(name = "zapowiedzFakturyZipFile", targetNamespace = "")
    public java.util.List<byte[]> getZapowiedziFaktur(
        @WebParam(name = "data", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar data
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/downloadIWDContent")
    @RequestWrapper(localName = "downloadIWDContent", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DownloadIWDContent")
    @ResponseWrapper(localName = "downloadIWDContentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DownloadIWDContentResponse")
    public void downloadIWDContent(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "IWDContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> iwdContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateReturnDocumentsProfile")
    @RequestWrapper(localName = "updateReturnDocumentsProfile", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateReturnDocumentsProfile")
    @ResponseWrapper(localName = "updateReturnDocumentsProfileResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateReturnDocumentsProfileResponse")
    public void updateReturnDocumentsProfile(
        @WebParam(name = "profile", targetNamespace = "")
        pocztex.test.packages.ReturnDocumentProfileType profile,
        @WebParam(mode = WebParam.Mode.OUT, name = "result", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "idProfile", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idProfile,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addShipment")
    @RequestWrapper(localName = "addShipment", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddShipment")
    @ResponseWrapper(localName = "addShipmentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddShipmentResponse")
    @WebResult(name = "retval", targetNamespace = "")
    public java.util.List<pocztex.test.packages.AddShipmentResponseItemType> addShipment(
        @WebParam(name = "przesylki", targetNamespace = "")
        java.util.List<pocztex.test.packages.PrzesylkaType> przesylki,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/cancelReklamacja")
    @RequestWrapper(localName = "cancelReklamacja", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CancelReklamacja")
    @ResponseWrapper(localName = "cancelReklamacjaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CancelReklamacjaResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> cancelReklamacja(
        @WebParam(name = "idRelkamacja", targetNamespace = "")
        int idRelkamacja
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/sendEnvelope")
    @RequestWrapper(localName = "sendEnvelope", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SendEnvelope")
    @ResponseWrapper(localName = "sendEnvelopeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SendEnvelopeResponseType")
    public void sendEnvelope(
        @WebParam(name = "urzadNadania", targetNamespace = "")
        java.lang.Integer urzadNadania,
        @WebParam(name = "pakiet", targetNamespace = "")
        java.util.List<pocztex.test.packages.PakietType> pakiet,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(name = "profil", targetNamespace = "")
        pocztex.test.packages.ProfilType profil,
        @WebParam(mode = WebParam.Mode.OUT, name = "idEnvelope", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeStatus", targetNamespace = "")
        javax.xml.ws.Holder<EnvelopeStatusType> envelopeStatus,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeFilename", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> envelopeFilename
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getJednostkaOrganizacyjna")
    @RequestWrapper(localName = "getJednostkaOrganizacyjna", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetJednostkaOrganizacyjna")
    @ResponseWrapper(localName = "getJednostkaOrganizacyjnaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetJednostkaOrganizacyjnaResponse")
    public void getJednostkaOrganizacyjna(
        @WebParam(name = "jednostka", targetNamespace = "")
        pocztex.test.packages.JednostkaOrganizacyjnaType jednostka,
        @WebParam(mode = WebParam.Mode.OUT, name = "jednostkaOrganizacyjna", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.JednostkaOrganizacyjnaType>> jednostkaOrganizacyjna,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateParcelContent")
    @RequestWrapper(localName = "updateParcelContent", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateParcelContent")
    @ResponseWrapper(localName = "updateParcelContentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateParcelContentResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> updateParcelContent(
        @WebParam(name = "parcelContent", targetNamespace = "")
        java.util.List<pocztex.test.packages.ParcelContentType> parcelContent
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeList")
    @RequestWrapper(localName = "getEnvelopeList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeList")
    @ResponseWrapper(localName = "getEnvelopeListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeListResponse")
    @WebResult(name = "envelopes", targetNamespace = "")
    public java.util.List<pocztex.test.packages.EnvelopeInfoType> getEnvelopeList(
        @WebParam(name = "startDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endDate
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddressLabel")
    @RequestWrapper(localName = "getAddressLabel", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddressLabel")
    @ResponseWrapper(localName = "getAddressLabelResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddressLabelResponse")
    public void getAddressLabel(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "content", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.AddressLabelContent>> content,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/deleteReturnDocumentsProfile")
    @RequestWrapper(localName = "deleteReturnDocumentsProfile", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DeleteReturnDocumentsProfile")
    @ResponseWrapper(localName = "deleteReturnDocumentsProfileResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DeleteReturnDocumentsProfileResponse")
    public void deleteReturnDocumentsProfile(
        @WebParam(name = "idProfile", targetNamespace = "")
        int idProfile,
        @WebParam(mode = WebParam.Mode.OUT, name = "result", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "idProfile", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idProfile1,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getKierunkiInfo")
    @RequestWrapper(localName = "getKierunkiInfo", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetKierunkiInfo")
    @ResponseWrapper(localName = "getKierunkiInfoResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetKierunkiInfoResponse")
    public void getKierunkiInfo(
        @WebParam(name = "plan", targetNamespace = "")
        java.lang.String plan,
        @WebParam(mode = WebParam.Mode.OUT, name = "lastUpdate", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> lastUpdate,
        @WebParam(mode = WebParam.Mode.OUT, name = "usluga", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.UslugiType>> usluga,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createReturnDocumentsProfile")
    @RequestWrapper(localName = "createReturnDocumentsProfile", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateReturnDocumentsProfile")
    @ResponseWrapper(localName = "createReturnDocumentsProfileResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateReturnDocumentsProfileResponse")
    public void createReturnDocumentsProfile(
        @WebParam(name = "profile", targetNamespace = "")
        pocztex.test.packages.ReturnDocumentProfileType profile,
        @WebParam(mode = WebParam.Mode.OUT, name = "result", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "idProfile", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idProfile,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAccountList")
    @RequestWrapper(localName = "getAccountList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAccountList")
    @ResponseWrapper(localName = "getAccountListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAccountListResponse")
    @WebResult(name = "account", targetNamespace = "")
    public java.util.List<pocztex.test.packages.AccountType> getAccountList();

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeBufor")
    @RequestWrapper(localName = "getEnvelopeBufor", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeBufor")
    @ResponseWrapper(localName = "getEnvelopeBuforResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeBuforResponse")
    public void getEnvelopeBufor(
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "przesylka", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.PrzesylkaType>> przesylka,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeContentFull")
    @RequestWrapper(localName = "getEnvelopeContentFull", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeContentFull")
    @ResponseWrapper(localName = "getEnvelopeContentFullResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeContentFullResponse")
    @WebResult(name = "przesylka", targetNamespace = "")
    public java.util.List<pocztex.test.packages.PrzesylkaFullType> getEnvelopeContentFull(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/wyslijLinkaOStatusieEZwrotu")
    @RequestWrapper(localName = "wyslijLinkaOStatusieEZwrotu", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.WyslijLinkaOStatusieEZwrotu")
    @ResponseWrapper(localName = "wyslijLinkaOStatusieEZwrotuResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.WyslijLinkaOStatusieEZwrotuResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> wyslijLinkaOStatusieEZwrotu(
        @WebParam(name = "guidZgodaEZwrot", targetNamespace = "")
        java.util.List<java.lang.String> guidZgodaEZwrot
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addRozbieznoscDoZapowiedziFaktur")
    @RequestWrapper(localName = "addRozbieznoscDoZapowiedziFaktur", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddRozbieznoscDoZapowiedziFaktur")
    @ResponseWrapper(localName = "addRozbieznoscDoZapowiedziFakturResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddRozbieznoscDoZapowiedziFakturResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> addRozbieznoscDoZapowiedziFaktur(
        @WebParam(name = "rozbieznosciZipFile", targetNamespace = "")
        java.util.List<byte[]> rozbieznosciZipFile
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/zamowKuriera")
    @RequestWrapper(localName = "zamowKuriera", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ZamowKuriera")
    @ResponseWrapper(localName = "zamowKurieraResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ZamowKurieraResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> zamowKuriera(
        @WebParam(name = "miejsceOdbioru", targetNamespace = "")
        pocztex.test.packages.AdresType miejsceOdbioru,
        @WebParam(name = "nadawca", targetNamespace = "")
        pocztex.test.packages.AdresType nadawca,
        @WebParam(name = "oczekiwanaDataOdbioru", targetNamespace = "")
        java.lang.String oczekiwanaDataOdbioru,
        @WebParam(name = "oczekiwanaGodzinaOdbioru", targetNamespace = "")
        java.lang.String oczekiwanaGodzinaOdbioru,
        @WebParam(name = "szacowanaIloscPrzeslek", targetNamespace = "")
        java.lang.String szacowanaIloscPrzeslek,
        @WebParam(name = "szacowanaLacznaMasaPrzesylek", targetNamespace = "")
        java.lang.String szacowanaLacznaMasaPrzesylek,
        @WebParam(name = "potwierdzenieZamowieniaEmail", targetNamespace = "")
        java.lang.String potwierdzenieZamowieniaEmail
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getUrzedyNadania")
    @RequestWrapper(localName = "getUrzedyNadania", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetUrzedyNadania")
    @ResponseWrapper(localName = "getUrzedyNadaniaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetUrzedyNadaniaResponse")
    @WebResult(name = "urzedyNadania", targetNamespace = "")
    public java.util.List<pocztex.test.packages.UrzadNadaniaFullType> getUrzedyNadania();

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeContentShort")
    @RequestWrapper(localName = "getEnvelopeContentShort", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeContentShort")
    @ResponseWrapper(localName = "getEnvelopeContentShortResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeContentShortResponse")
    @WebResult(name = "przesylka", targetNamespace = "")
    public java.util.List<pocztex.test.packages.PrzesylkaShortType> getEnvelopeContentShort(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/clearEnvelope")
    @RequestWrapper(localName = "clearEnvelope", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ClearEnvelope")
    @ResponseWrapper(localName = "clearEnvelopeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ClearEnvelopeResponse")
    public void clearEnvelope(
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "retval", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> retval,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateProfil")
    @RequestWrapper(localName = "updateProfil", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateProfil")
    @ResponseWrapper(localName = "updateProfilResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateProfilResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> updateProfil(
        @WebParam(name = "profil", targetNamespace = "")
        pocztex.test.packages.ProfilType profil
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/setStatusZgodyNaEZwrot")
    @RequestWrapper(localName = "setStatusZgodyNaEZwrot", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SetStatusZgodyNaEZwrot")
    @ResponseWrapper(localName = "setStatusZgodyNaEZwrotResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SetStatusZgodyNaEZwrotResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> setStatusZgodyNaEZwrot(
        @WebParam(name = "statusZgody", targetNamespace = "")
        java.util.List<pocztex.test.packages.StatusZgodyEZwrotType> statusZgody
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/moveShipments")
    @RequestWrapper(localName = "moveShipments", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.MoveShipments")
    @ResponseWrapper(localName = "moveShipmentsResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.MoveShipmentsResponse")
    public void moveShipments(
        @WebParam(name = "idBuforFrom", targetNamespace = "")
        int idBuforFrom,
        @WebParam(name = "idBuforTo", targetNamespace = "")
        int idBuforTo,
        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(mode = WebParam.Mode.OUT, name = "notMovedGuid", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<java.lang.String>> notMovedGuid,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeBuforList")
    @RequestWrapper(localName = "getEnvelopeBuforList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeBuforList")
    @ResponseWrapper(localName = "getEnvelopeBuforListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEnvelopeBuforListResponse")
    public void getEnvelopeBuforList(
        @WebParam(mode = WebParam.Mode.OUT, name = "bufor", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.BuforType>> bufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateChecklistTemplate")
    @RequestWrapper(localName = "updateChecklistTemplate", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateChecklistTemplate")
    @ResponseWrapper(localName = "updateChecklistTemplateResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateChecklistTemplateResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> updateChecklistTemplate(
        @WebParam(name = "checklistTemplate", targetNamespace = "")
        java.util.List<pocztex.test.packages.ChecklistTemplateType> checklistTemplate
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getListaPowodowReklamacji")
    @RequestWrapper(localName = "getListaPowodowReklamacji", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetListaPowodowReklamacji")
    @ResponseWrapper(localName = "getListaPowodowReklamacjiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetListaPowodowReklamacjiResponse")
    @WebResult(name = "kategoriePowodowReklamacji", targetNamespace = "")
    public java.util.List<pocztex.test.packages.KategoriePowodowReklamacjiType> getListaPowodowReklamacji();

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addZalacznikDoReklamacji")
    @RequestWrapper(localName = "addZalacznikDoReklamacji", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddZalacznikDoReklamacji")
    @ResponseWrapper(localName = "addZalacznikDoReklamacjiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddZalacznikDoReklamacjiResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> addZalacznikDoReklamacji(
        @WebParam(name = "idReklamacja", targetNamespace = "")
        java.lang.String idReklamacja,
        @WebParam(name = "zalacznik", targetNamespace = "")
        java.util.List<pocztex.test.packages.ZalacznikDoReklamacjiType> zalacznik
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createAccount")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateAccountResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> createAccount(
        @WebParam(name = "account", targetNamespace = "")
        pocztex.test.packages.AccountType account
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEZDO")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEZDOResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", partName = "parameters")
    public GetEZDOResponse getEZDO(
        @WebParam(partName = "parameters", name = "getEZDO", targetNamespace = "http://e-nadawca.poczta-polska.pl")
        GetEZDO parameters
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddresLabelByGuidCompact")
    @RequestWrapper(localName = "getAddresLabelByGuidCompact", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddresLabelByGuidCompact")
    @ResponseWrapper(localName = "getAddresLabelByGuidCompactResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddresLabelByGuidCompactResponse")
    public void getAddresLabelByGuidCompact(
        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getPlacowkiPocztowe")
    @RequestWrapper(localName = "getPlacowkiPocztowe", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetPlacowkiPocztowe")
    @ResponseWrapper(localName = "getPlacowkiPocztoweResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetPlacowkiPocztoweResponse")
    @WebResult(name = "placowka", targetNamespace = "")
    public java.util.List<pocztex.test.packages.PlacowkaPocztowaType> getPlacowkiPocztowe(
        @WebParam(name = "idWojewodztwo", targetNamespace = "")
        java.lang.String idWojewodztwo
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getListaZgodEZwrotow")
    @RequestWrapper(localName = "getListaZgodEZwrotow", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetListaZgodEZwrotow")
    @ResponseWrapper(localName = "getListaZgodEZwrotowResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetListaZgodEZwrotowResponse")
    public void getListaZgodEZwrotow(
        @WebParam(name = "status", targetNamespace = "")
        pocztex.test.packages.StatusZgodyEZwrotNameType status,
        @WebParam(mode = WebParam.Mode.OUT, name = "lista", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.OczekujeNaZgodeEZwrotType>> lista,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddresLabelByGuid")
    @RequestWrapper(localName = "getAddresLabelByGuid", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddresLabelByGuid")
    @ResponseWrapper(localName = "getAddresLabelByGuidResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetAddresLabelByGuidResponse")
    public void getAddresLabelByGuid(
        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "content", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.AddressLabelContent>> content,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/clearEnvelopeByGuids")
    @RequestWrapper(localName = "clearEnvelopeByGuids", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ClearEnvelopeByGuids")
    @ResponseWrapper(localName = "clearEnvelopeByGuidsResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.ClearEnvelopeByGuidsResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> clearEnvelopeByGuids(
        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getParcelContentList")
    @RequestWrapper(localName = "getParcelContentList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetParcelContentList")
    @ResponseWrapper(localName = "getParcelContentListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetParcelContentListResponse")
    public void getParcelContentList(
        @WebParam(name = "idKarta", targetNamespace = "")
        int idKarta,
        @WebParam(mode = WebParam.Mode.OUT, name = "parcelContent", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ParcelContentType>> parcelContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/uploadIWDContent")
    @RequestWrapper(localName = "uploadIWDContent", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UploadIWDContent")
    @ResponseWrapper(localName = "uploadIWDContentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SendEnvelopeResponseType")
    public void uploadIWDContent(
        @WebParam(name = "urzadNadania", targetNamespace = "")
        java.lang.Integer urzadNadania,
        @WebParam(name = "IWDContent", targetNamespace = "")
        byte[] iwdContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "idEnvelope", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeStatus", targetNamespace = "")
        javax.xml.ws.Holder<EnvelopeStatusType> envelopeStatus,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeFilename", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> envelopeFilename
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/hello")
    @RequestWrapper(localName = "hello", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.HelloResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getPasswordExpiredDate")
    @RequestWrapper(localName = "getPasswordExpiredDate", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetPasswordExpiredDate")
    @ResponseWrapper(localName = "getPasswordExpiredDateResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetPasswordExpiredDateResponse")
    @WebResult(name = "dataWygasniecia", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar getPasswordExpiredDate();

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/deleteChecklistTemplate")
    @RequestWrapper(localName = "deleteChecklistTemplate", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DeleteChecklistTemplate")
    @ResponseWrapper(localName = "deleteChecklistTemplateResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.DeleteChecklistTemplateResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> deleteChecklistTemplate(
        @WebParam(name = "checklistTemplate", targetNamespace = "")
        java.util.List<pocztex.test.packages.ChecklistTemplateType> checklistTemplate
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEZDOList")
    @RequestWrapper(localName = "getEZDOList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEZDOList")
    @ResponseWrapper(localName = "getEZDOListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetEZDOListResponse")
    @WebResult(name = "EZDOPakiet", targetNamespace = "")
    public java.util.List<pocztex.test.packages.EZDOPakietType> getEZDOList();

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getWplatyCKP")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getWplatyCKPResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", partName = "parameters")
    public GetWplatyCKPResponse getWplatyCKP(
        @WebParam(partName = "parameters", name = "getWplatyCKP", targetNamespace = "http://e-nadawca.poczta-polska.pl")
        GetWplatyCKP parameters
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addOdwolanieDoReklamacji")
    @RequestWrapper(localName = "addOdwolanieDoReklamacji", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddOdwolanieDoReklamacji")
    @ResponseWrapper(localName = "addOdwolanieDoReklamacjiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddOdwolanieDoReklamacjiResponse")
    public void addOdwolanieDoReklamacji(
        @WebParam(name = "reklamacja", targetNamespace = "")
        java.util.List<pocztex.test.packages.ReklamowanaPrzesylkaType> reklamacja,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "reklamacjaInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ReklamacjaInfoType>> reklamacjaInfo
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getReklamacje")
    @RequestWrapper(localName = "getReklamacje", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetReklamacje")
    @ResponseWrapper(localName = "getReklamacjeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetReklamacjeResponse")
    @WebResult(name = "reklamacja", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ReklamacjaRozpatrzonaType> getReklamacje(
        @WebParam(name = "dataRozpatrzenia", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dataRozpatrzenia
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEPOStatus")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEPOStatusResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", partName = "parameters")
    public GetEPOStatusResponse getEPOStatus(
        @WebParam(partName = "parameters", name = "getEPOStatus", targetNamespace = "http://e-nadawca.poczta-polska.pl")
        GetEPOStatus parameters
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/isMiejscowa")
    @RequestWrapper(localName = "isMiejscowa", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.IsMiejscowa")
    @ResponseWrapper(localName = "isMiejscowaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.IsMiejscowaResponse")
    @WebResult(name = "trasaResponse", targetNamespace = "")
    public java.util.List<pocztex.test.packages.TrasaResponseType> isMiejscowa(
        @WebParam(name = "trasaRequest", targetNamespace = "")
        java.util.List<pocztex.test.packages.TrasaRequestType> trasaRequest
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getProfilList")
    @RequestWrapper(localName = "getProfilList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetProfilList")
    @ResponseWrapper(localName = "getProfilListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetProfilListResponse")
    @WebResult(name = "profil", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ProfilType> getProfilList();

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateAccount")
    @RequestWrapper(localName = "updateAccount", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateAccount")
    @ResponseWrapper(localName = "updateAccountResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateAccountResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> updateAccount(
        @WebParam(name = "account", targetNamespace = "")
        pocztex.test.packages.AccountType account
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createEnvelopeBufor")
    @RequestWrapper(localName = "createEnvelopeBufor", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateEnvelopeBufor")
    @ResponseWrapper(localName = "createEnvelopeBuforResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateEnvelopeBuforResponse")
    public void createEnvelopeBufor(
        @WebParam(name = "bufor", targetNamespace = "")
        java.util.List<pocztex.test.packages.BuforType> bufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "createdBufor", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.BuforType>> createdBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getGuid")
    @RequestWrapper(localName = "getGuid", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetGuid")
    @ResponseWrapper(localName = "getGuidResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetGuidResponse")
    @WebResult(name = "guid", targetNamespace = "")
    public java.util.List<java.lang.String> getGuid(
        @WebParam(name = "ilosc", targetNamespace = "")
        int ilosc
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addReklamacje")
    @RequestWrapper(localName = "addReklamacje", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddReklamacje")
    @ResponseWrapper(localName = "addReklamacjeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.AddReklamacjeResponse")
    public void addReklamacje(
        @WebParam(name = "reklamowanaPrzesylka", targetNamespace = "")
        java.util.List<pocztex.test.packages.ReklamowanaPrzesylkaType> reklamowanaPrzesylka,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "reklamacjaInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ReklamacjaInfoType>> reklamacjaInfo
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/setJednostkaOrganizacyjna")
    @RequestWrapper(localName = "setJednostkaOrganizacyjna", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SetJednostkaOrganizacyjna")
    @ResponseWrapper(localName = "setJednostkaOrganizacyjnaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SetJednostkaOrganizacyjnaResponse")
    public void setJednostkaOrganizacyjna(
        @WebParam(mode = WebParam.Mode.INOUT, name = "jednostkaOrganizacyjna", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.JednostkaOrganizacyjnaType>> jednostkaOrganizacyjna,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getKarty")
    @RequestWrapper(localName = "getKarty", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetKarty")
    @ResponseWrapper(localName = "getKartyResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetKartyResponse")
    @WebResult(name = "karta", targetNamespace = "")
    public java.util.List<pocztex.test.packages.KartaType> getKarty();

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getKierunki")
    @RequestWrapper(localName = "getKierunki", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetKierunki")
    @ResponseWrapper(localName = "getKierunkiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetKierunkiResponse")
    public void getKierunki(
        @WebParam(name = "plan", targetNamespace = "")
        java.lang.String plan,
        @WebParam(name = "prefixKodPocztowy", targetNamespace = "")
        java.lang.String prefixKodPocztowy,
        @WebParam(mode = WebParam.Mode.OUT, name = "kierunek", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.KierunekType>> kierunek,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/setAktywnaKarta")
    @RequestWrapper(localName = "setAktywnaKarta", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SetAktywnaKarta")
    @ResponseWrapper(localName = "setAktywnaKartaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.SetAktywnaKartaResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> setAktywnaKarta(
        @WebParam(name = "idKarta", targetNamespace = "")
        int idKarta
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateShopEZwroty")
    @RequestWrapper(localName = "updateShopEZwroty", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateShopEZwroty")
    @ResponseWrapper(localName = "updateShopEZwrotyResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.UpdateShopEZwrotyResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> updateShopEZwroty(
        @WebParam(name = "shop", targetNamespace = "")
        pocztex.test.packages.ShopEZwrotyType shop
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getOutboxBook")
    @RequestWrapper(localName = "getOutboxBook", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetOutboxBook")
    @ResponseWrapper(localName = "getOutboxBookResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetOutboxBookResponse")
    public void getOutboxBook(
        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(name = "includeNierejestrowane", targetNamespace = "")
        java.lang.Boolean includeNierejestrowane,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getUbezpieczeniaInfo")
    @RequestWrapper(localName = "getUbezpieczeniaInfo", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetUbezpieczeniaInfo")
    @ResponseWrapper(localName = "getUbezpieczeniaInfoResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetUbezpieczeniaInfoResponse")
    @WebResult(name = "poziomyUbezpieczenia", targetNamespace = "")
    public java.util.List<pocztex.test.packages.UbezpieczeniaInfoType> getUbezpieczeniaInfo();

    /**
     * Metoda zwraca kolekcję szablonów list czynności.
     * 				Jeżeli nie przekazano elementów idChecklistTemplate metoda zwróci
     * 				wyłącznie kolekcję opisów szablonów list czynności. Jeżeli
     * 				przekazano elementy idChecklistTemplate metoda zwróci pełny opis
     * 				szablonu listy czynności.
     * 			
     */
    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getChecklistTemplateList")
    @RequestWrapper(localName = "getChecklistTemplateList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetChecklistTemplateList")
    @ResponseWrapper(localName = "getChecklistTemplateListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.GetChecklistTemplateListResponse")
    public void getChecklistTemplateList(
        @WebParam(name = "idChecklistTemplate", targetNamespace = "")
        java.util.List<java.lang.Integer> idChecklistTemplate,
        @WebParam(mode = WebParam.Mode.OUT, name = "checklistTemplate", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ChecklistTemplateType>> checklistTemplate,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pocztex.test.packages.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createProfil")
    @RequestWrapper(localName = "createProfil", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateProfil")
    @ResponseWrapper(localName = "createProfilResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pocztex.test.packages.CreateProfilResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pocztex.test.packages.ErrorType> createProfil(
        @WebParam(name = "profil", targetNamespace = "")
        pocztex.test.packages.ProfilType profil
    );
}
