package pocztex.test.tracking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-04-21T22:49:13.837+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://sledzenie.pocztapolska.pl", name = "SledzeniePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SledzeniePortType {

    @WebMethod(action = "urn:sprawdzPrzesylkiPl")
    @Action(input = "urn:sprawdzPrzesylkiPl", output = "urn:sprawdzPrzesylkiPlResponse")
    @RequestWrapper(localName = "sprawdzPrzesylkiPl", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkiPl")
    @ResponseWrapper(localName = "sprawdzPrzesylkiPlResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkiPlResponse")
    @WebResult(name = "return", targetNamespace = "http://sledzenie.pocztapolska.pl")
    public pocztex.test.tracking.Komunikat sprawdzPrzesylkiPl(
        @WebParam(name = "numer", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.util.List<java.lang.String> numer
    );

    @WebMethod(action = "urn:sprawdzPrzesylke")
    @Action(input = "urn:sprawdzPrzesylke", output = "urn:sprawdzPrzesylkeResponse")
    @RequestWrapper(localName = "sprawdzPrzesylke", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylke")
    @ResponseWrapper(localName = "sprawdzPrzesylkeResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkeResponse")
    @WebResult(name = "return", targetNamespace = "http://sledzenie.pocztapolska.pl")
    public pocztex.test.tracking.Przesylka sprawdzPrzesylke(
        @WebParam(name = "numer", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.lang.String numer
    );

    @WebMethod(action = "urn:sprawdzPrzesylkiOdDo")
    @Action(input = "urn:sprawdzPrzesylkiOdDo", output = "urn:sprawdzPrzesylkiOdDoResponse")
    @RequestWrapper(localName = "sprawdzPrzesylkiOdDo", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkiOdDo")
    @ResponseWrapper(localName = "sprawdzPrzesylkiOdDoResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkiOdDoResponse")
    @WebResult(name = "return", targetNamespace = "http://sledzenie.pocztapolska.pl")
    public pocztex.test.tracking.Komunikat sprawdzPrzesylkiOdDo(
        @WebParam(name = "numer", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.util.List<java.lang.String> numer,
        @WebParam(name = "odDnia", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.lang.String odDnia,
        @WebParam(name = "doDnia", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.lang.String doDnia
    );

    @WebMethod(action = "urn:sprawdzPrzesylki")
    @Action(input = "urn:sprawdzPrzesylki", output = "urn:sprawdzPrzesylkiResponse")
    @RequestWrapper(localName = "sprawdzPrzesylki", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylki")
    @ResponseWrapper(localName = "sprawdzPrzesylkiResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkiResponse")
    @WebResult(name = "return", targetNamespace = "http://sledzenie.pocztapolska.pl")
    public pocztex.test.tracking.Komunikat sprawdzPrzesylki(
        @WebParam(name = "numer", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.util.List<java.lang.String> numer
    );

    @WebMethod(action = "urn:sprawdzPrzesylkiOdDoPl")
    @Action(input = "urn:sprawdzPrzesylkiOdDoPl", output = "urn:sprawdzPrzesylkiOdDoPlResponse")
    @RequestWrapper(localName = "sprawdzPrzesylkiOdDoPl", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkiOdDoPl")
    @ResponseWrapper(localName = "sprawdzPrzesylkiOdDoPlResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkiOdDoPlResponse")
    @WebResult(name = "return", targetNamespace = "http://sledzenie.pocztapolska.pl")
    public pocztex.test.tracking.Komunikat sprawdzPrzesylkiOdDoPl(
        @WebParam(name = "numer", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.util.List<java.lang.String> numer,
        @WebParam(name = "odDnia", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.lang.String odDnia,
        @WebParam(name = "doDnia", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.lang.String doDnia
    );

    @WebMethod(action = "urn:witaj")
    @Action(input = "urn:witaj", output = "urn:witajResponse")
    @RequestWrapper(localName = "witaj", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.Witaj")
    @ResponseWrapper(localName = "witajResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.WitajResponse")
    @WebResult(name = "return", targetNamespace = "http://sledzenie.pocztapolska.pl")
    public java.lang.String witaj(
        @WebParam(name = "imie", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.lang.String imie
    );

    @WebMethod(action = "urn:sprawdzPrzesylkePl")
    @Action(input = "urn:sprawdzPrzesylkePl", output = "urn:sprawdzPrzesylkePlResponse")
    @RequestWrapper(localName = "sprawdzPrzesylkePl", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkePl")
    @ResponseWrapper(localName = "sprawdzPrzesylkePlResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", className = "pocztex.test.tracking.SprawdzPrzesylkePlResponse")
    @WebResult(name = "return", targetNamespace = "http://sledzenie.pocztapolska.pl")
    public pocztex.test.tracking.Przesylka sprawdzPrzesylkePl(
        @WebParam(name = "numer", targetNamespace = "http://sledzenie.pocztapolska.pl")
        java.lang.String numer
    );

    @WebMethod(action = "urn:wersja")
    @Action(input = "urn:wersja", output = "urn:wersjaResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "wersjaResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", partName = "parameters")
    public WersjaResponse wersja();

    @WebMethod(action = "urn:maksymalnaLiczbaPrzesylek")
    @Action(input = "urn:maksymalnaLiczbaPrzesylek", output = "urn:maksymalnaLiczbaPrzesylekResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "maksymalnaLiczbaPrzesylekResponse", targetNamespace = "http://sledzenie.pocztapolska.pl", partName = "parameters")
    public MaksymalnaLiczbaPrzesylekResponse maksymalnaLiczbaPrzesylek();
}
