package pocztex.test.tracking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-04-21T22:49:13.840+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "Sledzenie", 
                  wsdlLocation = "/home/mszwed/euvic/ws-couriers/src/main/resources/wsdl/pocztex_tracking.wsdl",
                  targetNamespace = "http://sledzenie.pocztapolska.pl") 
public class Sledzenie extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sledzenie.pocztapolska.pl", "Sledzenie");
    public final static QName SledzenieHttpEndpoint = new QName("http://sledzenie.pocztapolska.pl", "SledzenieHttpEndpoint");
    public final static QName SledzenieHttpSoap11Endpoint = new QName("http://sledzenie.pocztapolska.pl", "SledzenieHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("/home/mszwed/euvic/ws-couriers/src/main/resources/wsdl/pocztex_tracking.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Sledzenie.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/mszwed/euvic/ws-couriers/src/main/resources/wsdl/pocztex_tracking.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Sledzenie(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Sledzenie(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sledzenie() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sledzenie(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sledzenie(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sledzenie(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SledzeniePortType
     */
    @WebEndpoint(name = "SledzenieHttpEndpoint")
    public SledzeniePortType getSledzenieHttpEndpoint() {
        return super.getPort(SledzenieHttpEndpoint, SledzeniePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SledzeniePortType
     */
    @WebEndpoint(name = "SledzenieHttpEndpoint")
    public SledzeniePortType getSledzenieHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(SledzenieHttpEndpoint, SledzeniePortType.class, features);
    }
    /**
     *
     * @return
     *     returns SledzeniePortType
     */
    @WebEndpoint(name = "SledzenieHttpSoap11Endpoint")
    public SledzeniePortType getSledzenieHttpSoap11Endpoint() {
        return super.getPort(SledzenieHttpSoap11Endpoint, SledzeniePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SledzeniePortType
     */
    @WebEndpoint(name = "SledzenieHttpSoap11Endpoint")
    public SledzeniePortType getSledzenieHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(SledzenieHttpSoap11Endpoint, SledzeniePortType.class, features);
    }

}
